version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts_service_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
